jupyter/nbviewer

Dockerfile
README.md
nbviewer/static/less/notebook.less
nbviewer/static/less/styles.less
nbviewer/static/less/variables.less
nbviewer/templates/layout.html
nbviewer/templates/notebook.html
tasks.py

This adds LESS to build, combine and compress the CSS assets. It fixes #391, and reduces the number of  requests by a fair amont:
There is a new invoke task: `invoke less`. It can generate source maps.
This combines all of the CSS from `layout.html` into `static/build/styles.css` and all of the CSS from `notebook.html` into `static/build/notebook.css`.
Wherever possible, the existing CSS is being interpreted as LESS, so it can be compressed when served.
The Dockerfile now uses the invoke tasks.

Build less

---

nbviewer/templates/layout.html

Closes #397, adding Fastly as a sponsor.
I also took a redundant bit about the license in the footer which can also be found in the repo itself. I'd really like to get this footer cleaned up a bit more but this is it for now.
/cc @ejgreenberg

List Fastly as a sponsor

---

.travis.yml
Dockerfile
README.md
docker-compose.yml
nbviewer/handlers.py
nbviewer/render.py
requirements.txt
tasks.py

Hooray IPython 3.0 :cake:! Welcome to the future :monorail:!
This upgrades nbviewer's IPython requirement to `IPython[notebook]>=3.0`.
Since all good things come in threes, I'd love to see (IPython, Bootstrap & Reveal (ahem, #390)) 3.x all wrapped up as a 0.3.0 release!

Use IPython 3.0

---

nbviewer/app.py
setup.py

OK, time to come clean... I've had several local patches which make using the nbviewer as an internal service easier sitting on my machine for the last ~12 months.
The first is this one - the ability to use web proxies.
I've also slipped in the use of setuptools rather than distutils... slightly controversial, but let's move with the times... :wink: - I'd be happy to revert, it is just it makes working with the source easier as you can do ``python setup.py develop`` (simple things).

Added ability to use a web proxy.

---

Dockerfile

Deployment is getting a little behind IPython 3.x master. With the big split is coming, this might be the best way to have an image that is close to what is expected by upstream development.
Also some little movements of things that don't change much and were pretty late in the build.
And whitespace. Always whitespace.
@rgbkrk what were your reasons for not wanting to do this earlier?

Docker: FROM ipython/ipython:3.x

---

nbviewer/handlers.py
nbviewer/templates/layout.html

This totally doesn't seem to be working on http://nbviewer.ipython.org/url/jdj.mit.edu/~stevenj/IJulia%20Preview.ipynb
:-/
Posting this early to help with PyCon sprinters that want to touch the same stuff.

Parse robots.txt from originating URLs

---

nbviewer/frontpage.json
nbviewer/frontpage.schema.json
nbviewer/tests/test_json.py

This adds tests for well-formedness of JSON files that are part of the project, and fixes the invalid `frontpage.json` from #424. Instead of just parsing every JSON file in the project (think `node_modules`), I've just ticked them off explicitly.
`package.json` and `bower.json` are basically impossible to validate, but since we already have `jsonschema` around from IPython, I have added a schema for the front page. This should give us some good assurance of avoiding surprises in the future. Or something.

Test json files

---

setup.py

This fixes #448 by adding `providers` to `pkg_data`.
Props to @shmilee for reporting. As an aside: how did this bite you? I am a relative newcomer to the black arts of serious setup.py sorcery.

adding providers to pkg_data

---

nbviewer/static/less/slides.less
nbviewer/templates/formats/slides.html
nbviewer/templates/layout.html

This attempts to fix #433.
This solution is simple...
```css
body {overflow-y: auto}
```
...but is not ideal:
- it clobbers mobile UI swiping navigation between cells (and sub-cells)
- this really bothers me, because reveal is actually really nice on mobile. see below...
- because there is _always_ a scrollbar on the screen (if you use sub-cells, or have any long slides) you can never tell whether there _actually is_ somewhere to scroll.
However, other related solutions (i.e. making the `section` scrollable) ended up with scrollbars in the middle of the page, and much, much worse on mobile. reveal just looks too much at the DOM.
In the future :monorail:, with either nbconvert or nbviewer respecting more of reveal's options in notebook metadata, I recommend we peg this to the opposite of …

Restoring scrollable long slides

---

nbviewer/app.py
nbviewer/providers/local/handlers.py
nbviewer/tests/test_security.py

This adds tests and fixes for #471, #472 and #473.
As per @Carreau's suggestion, now using `autoescape` on the jinja2.Environment.
The localfile handler also will only serve files found under its path.
if someone really wants to fight for being able to allow escaping the directory they specify, i propose we put it behind a big gnarly config flag, i.e. `--very-insecure-traversal`.
I looked into a few tools for broader XSS exploration, but i think we'll have a lot of false positives... also, don't know which of them i can trust.

Template security

---

nbviewer/app.py
nbviewer/formats.py
nbviewer/providers/base.py
nbviewer/templates/notebook.html

It would be great if the nbviewer could handle numbered mathjax equations.
Check http://stackoverflow.com/questions/18823779/ipython-notebook-and-mathjax-labeled-equations
for more details

enable mathjax equation numbering by default

---

nbviewer/providers/base.py
nbviewer/providers/dropbox/handlers.py
nbviewer/providers/url/handlers.py
nbviewer/tests/test_utils.py
nbviewer/utils.py

This adds some more robust redirect URL handling with `urlunparse`.
As it was the source of the problem reported in #480, specifically for dropbox, it also strips the `?dl=.` which the upstream doesn't care about anyway. To allow that, the `?` param handling now occurs _after_ `url_rewrites`.
While I was in there testing, I handled #379, I think, as it was messing up my local test stuff (since I don't have/want/trust dropbox).
Would love some other eyes on this, as we should get it out pretty soon!

Fixing URL double-encode, dropbox-specifics

---

dev-requirements.txt
nbviewer/providers/github/handlers.py
nbviewer/providers/github/handlers_test.py
nbviewer/providers/github/tests/test_client.py
nbviewer/providers/github/tests/test_handlers.py
nbviewer/utils.py

Minor reorg to make unit testing providers easier.  Will get to #423 in time.
Makes uri translation function more accessible for tests and adds first pass for a github client that mocks out network communication.

Minor reorg for easier testing

---

nbviewer/templates/formats/slides.html

This is related with https://github.com/jupyter/nbconvert/pull/81

Remove Mathjax render on fragments-related events.

---

README.md

This was probably a leftover from #493, now that the name has changed for the dev requirements file.
/cc @bollwyvl

Swap order of dev and requirements and dev

---

nbviewer/app.py
nbviewer/providers/url/handlers.py
nbviewer/providers/url/tests/test_content.py
nbviewer/tests/async_base.py
nbviewer/tests/base.py
nbviewer/utils.py

JSON (and therefore all ipynb) should be served as utf-8.
This proposes that the url provider always use `utf-8` to decode what is coming back.
The default of [`ISO-8859-1`](https://github.com/jupyter/nbviewer/blob/4df8cfd919c87e03c029638b0b060555cd340c51/nbviewer/utils.py#L98) when `text/*` is received could stand, but maybe even it should be `utf-8`?

force utf-8 for notebook json requests

---

nbviewer/tests/test_security.py
nbviewer/utils.py

The github auth tokens leak in URL params on certain pages with next/prev links.
This doesn't really impact any confidential data: some joker might use up our quota, as I assume that token doesn't do anything else, but that has to be about it. Would need to refresh the keys anyway!
This might be a thing that should be pushed up into the providers, but this seemed like the most expedient place to fix it.
cc @Carreau @rgbkrk

GitHub url sanitizing

---

Dockerfile

Traceback for issue breaking the build for #494 below. Hooray, Unicode errors!
This just calls bower directly without using invoke. Doing some more local diagnostics to figure out where the issue lies (bower/invoke/us).
```python
Traceback (most recent call last):
File "/usr/local/bin/invoke", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.4/dist-packages/invoke/cli.py", line 438, in main
dispatch(sys.argv)
File "/usr/local/lib/python3.4/dist-packages/invoke/cli.py", line 431, in dispatch
return executor.execute(*tasks)
File "/usr/local/lib/python3.4/dist-packages/invoke/executor.py", line 100, in execute
task=task, name=name, args=args, kwargs=kwargs, config=config
File "/usr/local/lib/python3.4/dist-packages/invoke/executor.py", line 153, in _execute
result = …
```

manually calling bower

---

nbviewer/formats.py
nbviewer/static/less/slides.less
nbviewer/templates/nbconvert/slides_reveal.tpl

A resubmission of #511, but against the current pypi nbconvert (not master), to fix #506.
Adds a template path for nbconvert, the first use of which is used for a custom slides_reveal which just creates the body. This lets us get rid of the awful regex hack.
This is forked off of #508, whoops.

Slide templates

---

nbviewer/app.py
nbviewer/providers/local/tests/test_localfile.py
nbviewer/tests/base.py
nbviewer/tests/test_format_slides.py

- slides export can't handle empty notebooks, so use a notebook with a single markdown cell.
- run nbviewer test instance in a thread instead of a subprocess, which means we will get nice log capturing when tests fail, which makes fixing issues like the above a lot easier.

Testing fixes

---

nbviewer/app.py

and lower the default to 15 seconds.
It's actually this timeout that's causing the 503 errors on fastly, which has the same 20 second timeout, meaning that our slow renders never show the Working... page because fastly gives up immediately before the reply comes in.

make render_timeout an option

---

nbviewer/log.py
nbviewer/providers/base.py
nbviewer/providers/github/client.py

The root cause is actually tornadoweb/tornado#1582, where failure to construct requests could eventually prevent future requests from ever being made. On our side, this was caused by failure to quote GitHub paths, which resulted in UnicodeEncodeErrors in PyCurl. Once 10 requests had been made to non-ascii GitHub URLs, no subsequent requests would ever be made.
While digging into this, I reworked how we wait for concurrent requests by using Futures, and fixed a few bugs in our logging of failed requests.
closes #534

Fix recent 503 errors

---

nbviewer/templates/nbconvert/slides_reveal.tpl

This fixes #543 by bringing basically reverting to the middle commit of #512. Wasn't paying attention to the nbconvert release cycle, where a bunch of the slide stuff got fixed.
I've checked this out in Docker, looks solid.

bring slides up-to-date with nbconvert 4.1

---

nbviewer/providers/base.py

we've been triggering 'Waited 0.00s for concurrent request' on every non-unique request for a while now.

pop pending futures when they are done

---

Dockerfile

to get reduced validation errors, which clog up nbviewer logs (~70% of logs now are validation errors)

install nbformat from master in Dockerfile

---

nbviewer/app.py
nbviewer/providers/base.py
nbviewer/providers/gist/handlers.py
nbviewer/providers/github/handlers.py
nbviewer/providers/url/client.py
nbviewer/templates/error.html
nbviewer/utils.py

For servers that support If-None-Matching, If-Modified-Since cache headers, lean on upstream 304 responses for cache hit detection.
If an upstream request gives 304, the cached response is re-used.
Cached responses are saved for a hardcoded two hours, for now. Since we only support 304-based cache detection, a long expiry should not be a problem.
Since the GitHub API uses these headers and 304 responses don't count against your rate limit, this should significantly improve our rate limit consumption.
I also changed the error message when GitHub requests are failing due to the rate limit, so instead of a 400 with opaque "The error was: 403", it is a 503 error and explicitly mentions the GitHub rate limit and come back later.
closes #564

Cache upstream responses

---

nbviewer/providers/base.py

use integer division when truncating long strings

---

nbviewer/templates/layout.html

Help JS in a notebook know that it is executing on nbviewer. Makes it possible for notebooks to embed scripts meant only for nbviewer (e.g., https://gist.github.com/parente/4c3e6936d0d7a46fd071)

Add nbviewer CSS class to body tag

---

nbviewer/providers/gist/handlers.py

Allow >= 20 characters, rather than strictly 20 because gist IDs are now 32 characters, and there's no reason to be strict about it that I can see.

relax gist hash length regex

---

nbviewer/app.py

A new option `--no-check-certificate` was added to achieve this (I named the
option after `wget`'s option).
For example, to use the new option from the default docker container, do:
docker run -p 8080:8080 jupyter/nbviewer python3 -m nbviewer --port=8080 --no-check-certificate
Fixes #598.

Allow to disable SSL certificates validation

---

.travis.yml
requirements-dev.txt
tasks.py

Thanks to @ChristianKniep on #616, looks like `invoke` changed its API since last we tried to build stuff. This breaks the docker image, and of course local installation.
This is a quick fix, adding the `ctx` argument to each of the tasks, which is now the preferred way to call other tasks: i.e. `ctx.run` vs `invoke.run`.
Since travis has raised it's game significantly with respect to docker, I'm adding an explicit test of our docker stuff there to assist in testing against docker for future work. Another approach would be to have the dockerfile itself run the tests... really just a oneliner.

updating to invoke 0.13.0

---

nbviewer/providers/github/handlers.py

By default the behaviour stays the same. Now added an environment variable GITHUB_URL, in a similar fashion to the variable GITHUB_API_URL already in place by a previous patch. See #621

Fixed a bug on the Github Enterprise version of the github provider

---

nbviewer/app.py
nbviewer/providers/base.py
nbviewer/providers/local/handlers.py
nbviewer/templates/dirview.html

Allows navigation of directories under the localfiles root. Renders them in a page layout similar to the treelist template.

Add directory support to --localfiles

---

nbviewer/app.py
nbviewer/handlers.py

Need to prefix localfile format handlers with the base url too. Move the
code that adds the localfile handlers to the handlers modules so we can
take one prefixing pass through all the handlers, instead of worrying
about what is already prefixed vs not.

Fix localfile + base url + format support

---

nbviewer/providers/local/handlers.py
requirements.txt

Support a ?download query parameter on notebooks rendered
by the localfiles provider. Point the download header button
to the same URL with this arg attached to download local
notebook files.

Fix local provider download link

---

README.md

instead, we need to change the working directory to where nbviewer is located.

api_token is not needed for managed service

---

nbviewer/providers/github/client.py

logs show an error getting the message because `data` is a dict

log full message if message can't be extracted

---

nbviewer/app.py
nbviewer/providers/base.py
nbviewer/providers/github/client.py
nbviewer/providers/url/client.py
nbviewer/utils.py

- limit curl logging to INFO even when the rest of the app is debug-level because it logs way too much.
- promote some timings, cache hits, API rate limits to INFO

tweak debug and info-level log content

---

nbviewer/providers/github/client.py
nbviewer/providers/url/client.py

- Stop expiring cache of upstream responses. Since we still make a follow-up request, there is no cost in caching these as long as possible. Memcache will cleanup the oldest entries if it starts to fill up.
- When the follow-up request fails, re-use the cached response instead of failing.
- <del>Reduce load impact of bots on load by always using a cached response if there is one.</del> saving this for a later PR, since it's not as simple as I thought to tell what incoming request an outgoing request is on behalf of.

Increase upstream response caching

---

nbviewer/app.py
nbviewer/cache.py
nbviewer/providers/base.py
nbviewer/ratelimit.py

Recent usage is caused by crawlers triggering a bunch of renders. Most traffic has in fact been bots recently. Implementing a light rate limit should keep them from exhausting our GitHub API limit too easily.
Use memcache expiry for rate limiting. If cache dumps keys, rate limit might not be enforced, but that's not a huge deal.
default rate limit: 60 reqs / 10 minutes
Rate limit key is ip + user-agent. A bunch of users behind a router with the same browser will share a rate limit, but this shouldn't be a big issue. If they are visiting the same pages, they won't be bumping up the rate limit much because shared destinations will be in the cache.
Rate limit only applies to requests that would cost some work:
1. method is cached (most renderers, etc.), and
2. result is not *in* the cache, …

Implement rate limiting

---

nbviewer/app.py
nbviewer/handlers.py
nbviewer/providers/base.py
nbviewer/templates/index.html

I wanted to be able to turn off the input form on nbviewer when using it within my organisation and just direct navigation through the featured content.

Add no-frontpage-input option to hide input form in nbviewer

---

nbviewer/app.py

mathjax cdn is shutting down
cf https://www.mathjax.org/cdn-shutting-down/

get mathjax from cdnjs

---

Dockerfile

When trying to use docker for serving local notebooks with non-english names, by default it throws exception.
> [E 170524 20:58:22 concurrent:344] Future <tornado.concurrent.Future object at 0x7f2f96082b00> exception was never retrieved: Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 307, in wrapper
yielded = next(result)
File "/srv/nbviewer/nbviewer/providers/base.py", line 474, in cache_and_finish
self.write(content)
File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 717, in write
chunk = utf8(chunk)
File "/usr/local/lib/python3.4/dist-packages/tornado/escape.py", line 200, in utf8
return value.encode("utf-8")
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce5' in position 5189: surrogates not allowed
A …

Add default support for listing notebooks with non-english names in Docker

---

nbviewer/providers/base.py
nbviewer/providers/local/handlers.py
nbviewer/providers/url/tests/test_url.py
nbviewer/templates/layout.html

* Set directory name and filename as localfile page title
* Show path breadcrumbs for localfile notebooks
* Escape commas in download filenames

localfile navigation, naming improvements

---

nbviewer/handlers.py
nbviewer/providers/local/__init__.py
nbviewer/providers/local/handlers.py
tasks.py

I'm updating my org's instance of nbviewer which has fairly bespoke localfile usage (to access a network mounted disk). I'm going to be making further tweaks for the org (e.g. ensuring some security measures), but here was a quick win for this repo.
Essentially, the localfile provider is brought into line with the other providers by giving it a default_handlers function. We make use of that by appending the local provider as a string when localfile is enabled.

Tidy up the localfile handler a little.

---

nbviewer/providers/local/handlers.py

I've factored out a first-pass "can this be shown" function to the localfile provider. In order to minimise some of the risk of localfile, I wanted the ability to only show files that are readable by all. I've included that piece here too, as I think it is a sensible security measure, but would be happy to take it out again if necessary.
This change also now makes the checking of hidden files symmetrical - previously you could render a hidden subdirectory and/or notebook if you knew what address to type.

Factorise some of the localfile checking code.

---

nbviewer/handlers.py

This is necessary when starting nbviewer with ``--base-url`` if you want to be able to visit the top level of the base-level. For instance:
```
python -m nbviewer --base-url=/foo
```
I get a 404 at ```localhost:5000/foo```, but not at ```localhost:5000/foo/```. This change fixes that.
Ping @minrk as *I think* you added this feature for jupyterhub?

Make the top-level handler slash invariant.

---

README.md

The previous link 404'd as the documentation was reorganized to add a parent directory `reference`.

Fixes link to JupyterHub services documentation

---

.travis.yml
setup.py
tasks.py

- restore running invoke prior to build_py/sdist/develop,
which avoids installation missing the built files
- fix invocation of `pip download` for pip 10 (`pip.main` is gone)

Fixes for installation, pip 10

---

nbviewer/providers/local/handlers.py

We need to make UTC timestamps conform to true ISO-8601 by appending Z(ulu). Without a timezone, the spec says it should be treated as local time which is not what we want and causes moment.js on the frontend to show times in the past or future depending
on the user's timezone.
The code already assumes the server is providing UTC modification times by using datetime.utcfromtimestamp(). This PR just corrects the frontend rendering of that value.
https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators

Fix ISO 8601 formatting for moment.js

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general-question.md
README.md

Adding templates for feature requests, bug reports, and general questions. Including guidance about what to do if the feature/bug/question is not about nbviewer but rather another Jupyter project.

Add issue templates

---

nbviewer/app.py
nbviewer/providers/base.py

Adds a command line `--content_security_policy=<value>` option which becomes a `Content-Security-Policy: <value>` HTTP header in response to all requests. Makes it a little less scary to open notebooks of unknown origin and content.
The default value of `connect-src 'none';` is totally open for discussion but felt like a reasonable safeguard to me for people who might run the server locally. (It disallows XHR, WebSocket, Fetch, etc. to any domain.)

Add support for the Content-Security-Policy header

---

nbviewer/providers/url/tests/test_url.py
nbviewer/tests/test_utils.py
nbviewer/utils.py

[A comment](https://github.com/jupyter/nbviewer/issues/104#issuecomment-76996402) from @bollwyvl did not chime with my experience of nbviewer's handling of querystrings.
Given the suggestion, I assumed there was some code that was supposed to handle this, and indeed it appeared to be the case. For example, the url handler in [``nbviewer.handlers.url``](https://github.com/jupyter/nbviewer/blob/master/nbviewer/providers/url/handlers.py#L43) has a ``if '/?' in url:`` condition...
Turns out that this tiny bug fix turns on all the existing logic which wasn't currently being fired, and allows URLs with querystrings to be rendered, whilst maintaining the desire to user querysrtrings in the actual nbviewer URL (thus providing the ability to add querystrings to nbviewer in the future should they …

Fix URI transformation for query strings

---

nbviewer/app.py

While trying to figure out how `nbviewer` handles the tree navigation breadcrumb I found that function `format_handlers` is not used in `app.py` while at L#39 it has been imported.

Removed unused function from import

---

README.md

Fix the links to the externally managed JupyterHub services in `README.md`

Fix links to JupyterHub services

---

nbviewer/app.py
nbviewer/providers/base.py
nbviewer/templates/notebook.html
package.json
requirements.txt
tasks.py

* Add param to allow pinning to an older jupyter-widgets version (#818)
* Update bower to address npm audit recommendations
* Bump to using notebook 5.7.7 assets
* Pin to using tornado<6 until gen.Task and other hangs are resolved

General fixups

---

nbviewer/app.py
nbviewer/providers/base.py
nbviewer/templates/notebook.html
tasks.py

Allow specifying versions of jupyter-js-widgets and @jupyter-widgets/html-manager separately on the command line when launching nbviewer.
For #823, fixup for #818 workaround started in #821. Tested locally with 
```
python -m nbviewer --jupyter_js_widgets_version=2.1 --jupyter_widgets_html_manager_version=0.15
```
and pointing at the broken notebook in #823.

Hotfix for jupyter widgets support regression.

---

nbviewer/providers/local/handlers.py

- Added warning logs for instances where the `local` provider encounters file permission issues (https://github.com/jupyter/nbviewer/issues/828)

Additional logging for file permission issues

---

nbviewer/frontpage.json
nbviewer/templates/faq.md
requirements.txt

**(1)** Currently the Jinja2 in the `faq.md` file references a Python-Markdown extension, "HeaderId", which was removed from Python-Markdown in 2018; see this commit:
https://github.com/Python-Markdown/markdown/commit/11270135194922e0f5cfc739b69fe39f7337a0f9
Also, according to that commit, the HeaderId extension was deprecated and then removed from Python-Markdown because it can be replaced entirely by the `toc` extension, which is already referenced in the `faq.md` file.
Therefore, when trying to run nbviewer locally, with `faq.md`, and clicking on the FAQ link from the front page, one hits a "500 Internal Server Error" page, and the log files show that the error is
```ModuleNotFoundError: No module named 'headerid(level=3)'```.
After I removed the reference to `headerId` in `faq.md` and …

(1) Fixed FAQ page, (2) made front page compatible with JupyterHub

---

nbviewer/app.py
nbviewer/utils.py

Reorganized `init_tornado_application` by creating class properties for the `NBViewer` class, as well as a couple of attributes which are configurable traitlets (and thus can be modified from `nbviewer_config.py`). 
The main principle was: if the variable which was later used in `settings` depended on one of the `options.foo`, then for now the correct way to configure it should be exclusively through the command line (since the command line configuration is not yet compatible with traitlets), and so it should be made a property of the `NBViewer` class. 
Otherwise, it should be made a configurable traitlets instance, with a default value computed using the `@default` decorator from traitlets. 
However, I was not able to apply this principle to to `client` (using an instance of `Any`), …

Reorganize init_tornado_application, create some configurables

---

nbviewer/providers/github/handlers.py

Closes #863.
> **Describe the bug**
> When configured to integrate with GitHub Enterprise, links to repositories and users/orgs do not work.
> 
> Examples:
> 
>     * https://ghe.mycompany.com/ivangomes
> 
>     * https://ghe.mycompany.com/ivangomes/myproject
> 
> 
> **To Reproduce**
> Enter GHE URL like https://ghe.mycompany.com/ivangomes in an nbviewer deployment configured with GHE.
> 
> **Expected behavior**
> Get redirected to https://nbviewer.mycompany.com/github/ivangomes and see the navigation UI, like in https://nbviewer.jupyter.org/github/jupyter/nbviewer/tree/master/
> 
> **Additional context**
> Related to #850.

Fix repo and user links for GHE

---

nbviewer/providers/github/handlers.py

Closes #867.
> **Describe the bug**
> When configured to integrate with GitHub Enterprise, raw download links for notebooks do not work.
> 
> **To Reproduce**
> With a notebook from GHE open, e.g. https://nbviewer.mycompany.com/github/ivangomes/myproject/index.ipynb, in an nbviewer configured GITHUB_API_URL=https://ghe.mycompany.com/v3/api/, click the download button on the top right and get a 404.
> 
> **Expected behavior**
> File download from GHE starts.
> 
> **Additional context**
> Related to #850, #863, #865.

Fix raw download for GHE

---

nbviewer/providers/base.py

replace line 15 of providers/base.py with
`from html import escape`

Fix #869 from cgi import escape fails under python 3.8; import from html instead

---

nbviewer/providers/github/client.py
nbviewer/providers/url/client.py

we have never used it and it is removed in tornado 6
since we are still passing callback=None, this is causing upstream errors not to be raised, since raise_errors is now the second positional argument and we are effectively passing `raise_errors=None`, which, being Falsy, suppresses upstream request errors.

remove unused callback argument in fetch

---

nbviewer/handlers.py

<del>needs to be awaited</del>
turns out the async prepare didn't work in the 404 handler! We only got past this because we weren't waiting for the result. Better to skip altogether than start and never await it.

BaseHandler.prepare is async now

---

nbviewer/app.py
nbviewer/frontpage.json
nbviewer/providers/base.py
nbviewer/templates/index.html
nbviewer/templates/layout.html
requirements.txt

Changes to static file handling to facilitate customization. In particular, custom static paths now behave the same way that custom template paths do.
This involved changing the `static_url` method of `BaseHandler` to be different from the Tornado default. Moreover, the custom static file handler from notebook (instead of the default Tornado static file handler) is used (since it supports loading static files from multiple directories).

Step7_6 (custom static path now behaves same as custom template path)

---

README.md
nbviewer/app.py

For traitlets, the CLI specified value _always_ overwrites the available default, whereas for `base_url` we want the opposite behavior, i.e. for the default (an environment variable) to _always_ overwrite the CLI specified value, if the default is available.
Therefore, the solution I thought of was to make the "true" value of base url private, and to have the value specified on the CLI to just be the back-up value in case the `JUPYTERHUB_SERVICE_PREFIX` environment variable isn't available. 
Come to think of it, this behavior should probably be explicitly documented somewhere, since it might be counterintuitive to someone expecting typical traitlets behavior.

Step7_7 (prepare base_url for traitlets by making it "private")

---

README.md
nbviewer/app.py
nbviewer/tests/test_app.py

Note that `options.answer_yes`, `options.generate_config`, and `options.config_file` will all be turned into traitlets upon the transfer from `tornado.options` to `traitlets`. Writing them as `tornado.options` for now was just a provisional step so I could write this commit before the `tornado.options -> traitlets` commit, which will necessarily have a large diff. So splitting as much off from that diff as possible seems optimal.

Step7_8 (Add ability to write default config file)

---

nbviewer/app.py
nbviewer/formats.py

Make configure_formats a method of `NBViewer` to prepare for deletion of the options object with transition from `tornado.options` to `traitlets`.
In particular, the `configure_formats` function as written in `formats.py` depended on the `options` argument created by `tornado.options` in order to access the value of "`options.processes`".
After the transition from `tornado.options` to `traitlets`, any reference to `options.processes` will need to be replaced by a reference to `self.processes` inside of the `NBViewer` class. Therefore in order to access that value, `configure_formats` needs to be a method of `NBViewer`. 
(Or somehow it would be necessary to pass the entire application to `configure_formats`, if it were left as its own standalone function in `formats.py`, and then access …

Step7_10 (Make configure_formats method of NBViewer)

---

nbviewer/app.py
nbviewer/handlers.py
nbviewer/providers/base.py
nbviewer/providers/gist/handlers.py
nbviewer/providers/github/client.py
nbviewer/providers/github/handlers.py
nbviewer/providers/github/tests/test_client.py
nbviewer/providers/local/handlers.py
nbviewer/providers/url/client.py
nbviewer/providers/url/handlers.py
nbviewer/tests/base.py
nbviewer/utils.py

Unify all logging to a central log which is an attribute of the NBViewer class. Update format of logs to resemble that of other Jupyter applications, and to be more informative.
This involves a _temporary_ regression, since in order to use the `log_level` attribute of  `traitlets.config.Application`, and set it to `DEBUG` level via a command line flag, it is necessary to activate `traitlets` parsing of command line arguments, which can't be initiated until the migration of all `tornado.options` to `traitlets` is complete. I believe this is the reason why I previously had the changes to the logging and the entire migration to `traitlets` in one massive commit: I wanted to avoid any commits with even temporary feature regressions.
Again however this will involve zero loss of features, and …

Step7_11 (Unify and update logging)

---

README.md
nbviewer/templates/faq.md
nbviewer/templates/layout.html

\* partially for now, soon to be fully moved over

nbviewer.jupyter.org is now* hosted on OVH

---

nbviewer/index.py
requirements.txt

Pin to pre-6.0.0 version to avoid the build from breaking due to changes into the nbconvert library since v6.

Pin nbconvert version to fix #958

---

.pre-commit-config.yaml
nbviewer/providers/github/client.py
nbviewer/providers/github/handlers.py

This addresses the issue where the github repo/user URL in  nbviewer defaults to master. Instead we pull the value of default_branch from the GH API and and use that. 
Note that I didn't change the uri_rewrites because I don't think these are being used - but let me know if I missed something.

switch master to default branch

---

nbviewer/frontpage.json

Addressing #826, this change removes links that either go to 404 pages or to pages with broken embeds of images. I based these changes on a quick browse through nbviewer.org earlier today, viewing each link to see whether it refers to an existing file with all embeds intact.

Removes broken links (404s and pages with missing visualizations)

---

setup.py

Adding project URLs (especially source code URL) makes it easier for dependency management tools (like Renovate).

Add project URLs to setup.py

---

README.md
nbviewer/providers/__init__.py
nbviewer/providers/huggingface/__init__.py
nbviewer/providers/huggingface/handlers.py
nbviewer/templates/index.html
nbviewer/tests/test_utils.py

Hi!
I use https://nbviewer.org/ quite a bit and we are also considering implementing a notebook-rendering service on [huggingface.co](https://huggingface.co) that could potentially be built on top of nbconvert and/or nbviewer.
As a quick useful feature, I added URL rewrite from huggingface "blob" URLs, i.e. those you get when navigating to a ipynb file inside a repository, to the "resolve" URLs which we use to serve actual content.
This works for both:
- files stored in raw git: e.g. https://huggingface.co/pceiyos/fake_news_detection_nlp/blob/main/Fake_News_Classificaton.ipynb
- files stored in LFS, i.e. large notebooks over 10MB (also related to #664): https://huggingface.co/spaces/NimaBoscarino/climategan/blob/main/notebooks/plot_metrics.ipynb
Let me know if this looks ok!

Add provider for huggingface.co: Very basic `uri_rewrites`

---

nbviewer/providers/github/handlers.py

path and ref were swapped
this prevented tree listings from working

fix arg order in github internal_get

---

nbviewer/app.py

This PR is related to the problem identified in https://github.com/jupyter/docker-stacks/issues/1862 .
When a `JUPYTERHUB_SERVICE_URL` is received with port number 0 (which is a [valid usecase according to @minrk](https://github.com/jupyterhub/jupyterhub/pull/4310#discussion_r1087651448), some mechanism triggers which causes the Jupyter server to start running on port 80 instead of the default port 8888. Even when a `JUPYTER_PORT` environment variable is set, this value is ignored. I'm not sure where/why this exactly happens. 
This seems to be the only place where `JUPYTERHUB_SERVICE_URL` is parsed. When an invalid port number `0` is received, I think it is best to log a warning and revert to the default port `5000` instead.

Validate JUPYTERHUB_SERVICE_URL port number

---

.github/workflows/image.yaml

Hi all, a colleague highlighted to me that this repo is using `set-output` within GitHub Actions, and that this has now been deprecated, with guidance provided for replacing:
[GitHub Actions: Deprecating save-state and set-output commands - GitHub Changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Thanks!

Replace `set-output` with `$GITHUB_OUTPUT`

---

nbviewer/templates/layout.html

This adds a link to jupytercon 2025 in the navbar. I couldn't figure out how to make a banner header, so I added it as an additional link. Hopefully it is minimal enough that it wouldn't be disruptive. Here's a screenshot of what it looks like:

Add jupytercon link to navbar
