nbviewer/frontpage.json
Noticed that @camdavidsonpilon had changed the URL of the initial chapter, so I updated it here.
In addition, I moved a newer notebook up and took out some older notebooks from 2012.
@twiecki, I cut a gist of yours out that had deprecated bits from Pandas. Would you be happy with swapping to https://github.com/twiecki/financial-analysis-python-tutorial or would you rather submit a different notebook in its place?
=> Frontpage updates

nbviewer/frontpage.json
=> 2.x -> 3.x in frontpage.json

nbviewer/cache.py
=> Typo. The simplest little things.

nbviewer/handlers.py
Totally weren't catching 404s on robots.txt from #442.
=> Don't completely die out when robots.txt not found

nbviewer/frontpage.json
the location of the notebook has been changed
=> update link to iruby notebook

README.md
=> Absolute link to propsed providers

nbviewer/app.py, nbviewer/utils.py
Had to rebuild my nbviewer environment, and started seeing a bunch of deprecation warnings on run.
These may indeed break the 2.7 build, but we'll see what travis says :)
=> squashing deprecation warnings

nbviewer/templates/layout.html
=> s/web site/website/

README.md
Another room we don't use much that ends up getting diverted to jupyter/jupyter.
=> Delete the gitter badge

nbviewer/providers/github/handlers.py, nbviewer/providers/github/tests/test_handlers.py
PR for issue #587 .
With tests.
Sorry for complicated PR.
=> Add rewrite rules for Github Enterprise.

nbviewer/app.py, nbviewer/providers/base.py, nbviewer/utils.py, requirements.txt
=> Send metrics via statsd

nbviewer/templates/notebook.html
notebook package isn't used by nbviewer
=> remove notebook version from footer

nbviewer/static/less/variables.less
rather than bootstrap default of 1.25 x base
closes #604
=> set blockquote font-size to inherit

nbviewer/providers/gist/handlers.py
The gist API casts all file content to text without mentioning this, so images in gists are corrupted.
Always use the bytes from the raw URL for `image/*` mime types.
closes #611
=> use raw files for gist images

tasks.py
I replaced the harcoded call to pypi.org with the use of pip. This allows to use the configuration of pip transparently, in case there is an internal mirror to use, and simplify the import
=> Change hardcoded url to a call to pip

nbviewer/frontpage.json
We updated the urls in Bayesian Methods for Hackers (new PyMC3 version is available), so this PR changes the urls on the frontpage too. 
cc @Carreau for review
=> update link to new asset

nbviewer/app.py, nbviewer/handlers.py, nbviewer/providers/base.py, nbviewer/providers/gist/handlers.py, nbviewer/providers/github/handlers.py, nbviewer/templates/error.html, nbviewer/templates/formats/slides.html, nbviewer/templates/index.html, nbviewer/templates/layout.html, nbviewer/templates/notebook.html, nbviewer/templates/popular.html, nbviewer/templates/tabular.html, nbviewer/templates/treelist.html, nbviewer/templates/usergists.html, nbviewer/templates/userview.html
Make nbviewer relocatable behind a proxy (e.g., as a Jupyter Hub service)
=> Support --base-url

nbviewer/app.py
Include base_url for localfile provider.
=> Fix for #640

nbviewer/templates/layout.html
=> Add jupyter-js-widgets embedder

nbviewer/providers/local/handlers.py, nbviewer/templates/dirview.html, requirements.txt
Show the last modified time of files and directories
=> Add mod time to local provider

nbviewer/templates/faq.md
=> edit the faq - Include lets encrypt free SSL certificate info

nbviewer/providers/local/handlers.py, nbviewer/templates/dirview.html
Show time from now instead of UTC time in directory view of local files.
=> display time from now instead of UTC time

nbviewer/app.py, nbviewer/providers/base.py, nbviewer/templates/layout.html
=> get google analytics id from env

requirements.txt
Next release should have a fix
closes #677
=> Blacklist known-bad newrelic release

nbviewer/static/less/layout.less
Make nbviewer .fa rule more specific than the one in ipywidgets
=> Fix #658: Menu icon alignment

.gitignore, .travis.yml, nbviewer/app.py, tasks.py
will get new table styles from notebook 5.0
=> mathjax 2.7.1, notebook 5.0.0

setup.cfg, setup.py
call it 1.0 and update a couple of links in setup.py
closes #704
=> prepare to put it on pypi

tasks.py
=> bump bundled notebook version

nbviewer/app.py, nbviewer/providers/local/handlers.py
=> implement "--localfile_only_world_readable" command line switch

nbviewer/app.py, nbviewer/providers/local/handlers.py
=> implement the "--localfile_abspath" command line switch

nbviewer/templates/faq.md
=> Update the FAQ

requirements.txt
To resolve #692, this PR take in this commit:
https://github.com/jupyter/nbconvert/commit/792f285ef49230818ae4fa0701d3bd79a0820c2b
=> Upgrade nbconvert dependency

nbviewer/static/less/custom.less, nbviewer/static/less/styles.less, tasks.py
=> Support a custom.less extension point

nbviewer/formats.py
See https://github.com/jupyter/nbviewer/pull/710#issuecomment-450582398
=> Improve slide format detection

nbviewer/formats.py
b72a3da54954cd210049add84f22f1d028366b482afbff0697a4c186a2849c5774861309750b3a17cd9f2801f87c6358564916c9ad137240e7cf35b44aba9f44
=> Better slide detect

nbviewer/templates/faq.md
This is an implementation of the feature request found in this issue:
https://github.com/jupyter/nbviewer/issues/834
=> Update the FAQ to point people to the Discourse

nbviewer/providers/github/handlers.py, nbviewer/providers/url/handlers.py
Fixes #835. 
To test, see the Docker image [found here](https://github.com/krinsman/jupyterhub-deploy/tree/master/github_url_fix) and follow the instructions in the README.
=> Fixes #835 and #324

nbviewer/app.py
=> Fix P vs p typo

nbviewer/providers/github/handlers.py
github_url is corrected to the corresponding URL.
#850
=> fix for Github Enterprise

nbviewer/providers/base.py
=> Don't print the settings in self.statsd

README.md
I found a few typos in the README.md and wanted to resolve them! Hope it helps.
=> Fix typos in root README.md

nbviewer/providers/gist/handlers.py
Closes #865.
> **Describe the bug**
> When configured to integrate with GitHub Enterprise, Gists do not work.
> 
> **To Reproduce**
> Enter Gist URL, e.g. https://ghe.mycompany.com/gist/c3ca62e42d590f81c3a906824b2528b0, in an nbviewer configured `GITHUB_API_URL=https://ghe.mycompany.com/v3/api/`.
> 
> **Expected behavior**
> The notebook in the Gist is rendered in nbviewer.
> 
> **Additional context**
> Related to #850 and #863.
=> Fix Gist support with GHE

README.md
=> Step 7_1 (Add gitter link to README)

README.md, nbviewer/cache.py, nbviewer/handlers.py, nbviewer/providers/base.py, nbviewer/providers/gist/handlers.py, nbviewer/providers/github/handlers.py, nbviewer/providers/github/tests/test_client.py, nbviewer/providers/local/handlers.py, nbviewer/tests/async_base.py, nbviewer/tests/base.py, nbviewer/tests/test_config.py, nbviewer/tests/test_security.py
remove python 2 super statements and one unused import
=> remove python2 super syntax

nbviewer/providers/base.py
Alphabetize BaseHandler properties -- this makes it much easier to find and modify relevant parts of the code, at least in my experience.
=> alphabetize BaseHandler properties

nbviewer/app.py
Alphabetize nbviewer application attributes, properties, settings, and options. This PR will make the git diff for the changing of tornado options to traitlets easier to read.
=> alphabetize NBViewer settings

nbviewer/app.py, nbviewer/handlers.py, nbviewer/providers/github/handlers.py
Make `CreateHandler`, `Custom404Handler`, `FAQHandler`, `IndexHandler`, and `GithubUserHandler` customizable.
=> Step7_5 (make additional handlers customizable)

README.md, nbviewer/app.py
Prepare host and port for traitlets refactor and accompanying deletion of init_options
=> Step7_9 (Create function calculating default host and port)

helm-chart/nbviewer/values.yaml
it's building at nbviewer-statuspage
=> update statuspage image name

nbviewer/frontpage.json
cc @minrk 
Please let me know if there is anything else that needs to be done to remove Bokeh from the nbviewer.org site.
=> Remove Bokeh links

helm-chart/nbviewer/requirements.yaml
=> update memcached repo

nbviewer/frontpage.json
broken link : https://nbviewer.jupyter.org/url/jakevdp.github.com/downloads/notebooks/XKCD_plots.ipynb
fixed link : https://nbviewer.jupyter.org/url/jakevdp.github.io/downloads/notebooks/XKCD_plots.ipynb
=> Fix broken link

.github/workflows/image.yaml
autobuilds on DockerHub have stopped, so publish from our own CI
=> add image-building to GHA

nbviewer/providers/base.py
=> Fix link to alternate formatters (slides, code)
